'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { BookOpen, BrainCircuit, CheckCircle, Home, Loader2, Repeat, XCircle } from 'lucide-react';

import { generateMCQQuiz, type GenerateMCQQuizOutput } from '@/ai/flows/generate-mcq-quiz';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from '@/components/ui/card';
import { Form, FormControl, FormField, FormItem, FormMessage } from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';
import { cn } from '@/lib/utils';

type QuizQuestion = GenerateMCQQuizOutput['questions'][0];
type AppState = 'topic' | 'loading' | 'quiz' | 'results';

const formSchema = z.object({
  topic: z.string().min(3, 'Topic must be at least 3 characters long.').max(50, 'Topic must be 50 characters or less.'),
});

export default function QuizApp() {
  const [appState, setAppState] = useState<AppState>('topic');
  const [quizData, setQuizData] = useState<GenerateMCQQuizOutput | null>(null);
  const [topic, setTopic] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [isAnswered, setIsAnswered] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: { topic: '' },
  });

  const handleTopicSubmit = async (values: z.infer<typeof formSchema>) => {
    setIsLoading(true);
    setTopic(values.topic);
    setAppState('loading');
    try {
      const quiz = await generateMCQQuiz({ topic: values.topic });
      if (!quiz || !quiz.questions || quiz.questions.length === 0) {
        throw new Error('No questions were generated.');
      }
      setQuizData(quiz);
      setAppState('quiz');
    } catch (error) {
      console.error(error);
      toast({
        title: 'Error Generating Quiz',
        description: 'Failed to generate the quiz. Please try a different topic.',
        variant: 'destructive',
      });
      setAppState('topic');
    } finally {
      setIsLoading(false);
    }
  };

  const handleAnswerSubmit = () => {
    if (selectedAnswer === null) return;
    setIsAnswered(true);
    const currentQuestion = quizData!.questions[currentQuestionIndex];
    if (selectedAnswer === currentQuestion.correctAnswerIndex) {
      setScore((prev) => prev + 1);
    }
  };

  const handleNextQuestion = () => {
    setIsAnswered(false);
    setSelectedAnswer(null);
    if (currentQuestionIndex < quizData!.questions.length - 1) {
      setCurrentQuestionIndex((prev) => prev + 1);
    } else {
      setAppState('results');
    }
  };

  const restartQuiz = (newTopic = false) => {
    form.reset();
    setQuizData(null);
    setTopic('');
    setCurrentQuestionIndex(0);
    setScore(0);
    setSelectedAnswer(null);
    setIsAnswered(false);
    setAppState(newTopic ? 'topic' : 'loading');

    if (!newTopic && quizData) {
        handleTopicSubmit({ topic: quizData.questions[0] ? topic : 'General Knowledge' });
    }
  };

  const renderTopicSelector = () => (
    <Card className="w-full max-w-lg shadow-lg animate-in fade-in duration-500">
      <CardHeader className="text-center">
        <div className="flex justify-center items-center gap-2">
            <BrainCircuit className="w-6 h-6 md:w-8 md:h-8 text-primary" />
            <CardTitle className="text-2xl md:text-3xl font-bold">Quick Test AI</CardTitle>
        </div>
        <CardDescription>Enter any topic and get a 10-question quiz generated by AI.</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={form.handleSubmit(handleTopicSubmit)} className="space-y-6">
            <FormField
              control={form.control}
              name="topic"
              render={({ field }) => (
                <FormItem>
                  <FormControl>
                    <Input placeholder="e.g., 'The Roman Empire' or 'React.js Hooks'" {...field} className="text-center text-sm md:text-base" />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />
            <Button type="submit" className="w-full" disabled={isLoading}>
              {isLoading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : 'Generate Quiz'}
            </Button>
          </form>
        </Form>
      </CardContent>
    </Card>
  );

  const renderLoading = () => (
    <div className="flex flex-col items-center justify-center gap-4 text-center animate-in fade-in duration-500">
      <Loader2 className="w-10 h-10 md:w-12 md:h-12 text-primary animate-spin" />
      <h2 className="text-xl md:text-2xl font-semibold">Generating your quiz...</h2>
      <p className="text-muted-foreground max-w-sm">Please wait while we create questions on "{topic}".</p>
    </div>
  );

  const renderQuiz = () => {
    if (!quizData) return null;
    const currentQuestion = quizData.questions[currentQuestionIndex];
    const progress = ((currentQuestionIndex + 1) / quizData.questions.length) * 100;

    const getOptionStyle = (index: number) => {
        if (!isAnswered) {
          return selectedAnswer === index
            ? 'bg-primary/10 border-primary'
            : 'border-border';
        }
        if (index === currentQuestion.correctAnswerIndex) {
          return 'bg-accent/20 border-accent text-accent-foreground';
        }
        if (index === selectedAnswer) {
          return 'bg-destructive/20 border-destructive text-destructive-foreground';
        }
        return 'border-border opacity-60';
      };

    return (
      <div className="w-full max-w-2xl" key={currentQuestionIndex}>
        <div className="mb-4 animate-in fade-in duration-500">
          <div className="flex justify-between items-center mb-2 text-sm text-muted-foreground">
            <span>Question {currentQuestionIndex + 1} of {quizData.questions.length}</span>
            <span>Score: {score}</span>
          </div>
          <Progress value={progress} />
        </div>
        <Card className="shadow-lg animate-in fade-in-0 slide-in-from-bottom-5 duration-500">
          <CardHeader>
            <CardTitle className="text-lg md:text-xl lg:text-2xl leading-relaxed">{currentQuestion.question}</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {currentQuestion.options.map((option, index) => (
              <Button
                key={index}
                variant="outline"
                className={cn(
                    'w-full h-auto justify-start text-left py-3 px-4 whitespace-normal transition-all duration-300 text-sm md:text-base',
                    getOptionStyle(index)
                )}
                onClick={() => !isAnswered && setSelectedAnswer(index)}
                disabled={isAnswered}
              >
                <div className="flex items-center w-full">
                    <span className="flex-1">{option}</span>
                    {isAnswered && index === currentQuestion.correctAnswerIndex && <CheckCircle className="w-5 h-5 text-accent" />}
                    {isAnswered && index === selectedAnswer && index !== currentQuestion.correctAnswerIndex && <XCircle className="w-5 h-5 text-destructive" />}
                </div>
              </Button>
            ))}
          </CardContent>
          <CardFooter className="flex flex-col items-stretch">
            {isAnswered && (
                <div className="w-full p-4 mb-4 rounded-lg bg-secondary text-secondary-foreground animate-in fade-in duration-500">
                    <div className="flex items-start gap-3">
                        <BookOpen className="w-5 h-5 mt-1 text-primary flex-shrink-0" />
                        <div>
                            <h4 className="font-bold">Explanation</h4>
                            <p className="text-sm">{currentQuestion.explanation}</p>
                        </div>
                    </div>
                </div>
            )}
            <Button onClick={isAnswered ? handleNextQuestion : handleAnswerSubmit} disabled={selectedAnswer === null && !isAnswered} className="w-full">
              {isAnswered ? (currentQuestionIndex === quizData.questions.length - 1 ? 'Finish Quiz' : 'Next Question') : 'Submit Answer'}
            </Button>
          </CardFooter>
        </Card>
      </div>
    );
  };
  
  const renderResults = () => {
    const percentage = Math.round((score / quizData!.questions.length) * 100);
    let feedback = { title: "", description: "" };

    if (percentage === 100) {
        feedback = { title: "Perfect Score!", description: "Incredible! You're an expert on this topic." };
    } else if (percentage >= 80) {
        feedback = { title: "Excellent Work!", description: "You have a strong understanding of the material." };
    } else if (percentage >= 50) {
        feedback = { title: "Good Effort!", description: "You're on the right track. A little review could help." };
    } else {
        feedback = { title: "Keep Studying!", description: "Don't be discouraged. Learning is a journey." };
    }


    return (
        <Card className="w-full max-w-lg text-center shadow-lg animate-in zoom-in-95 duration-500">
            <CardHeader>
                <CardTitle className="text-2xl md:text-3xl font-bold">{feedback.title}</CardTitle>
                <CardDescription>{feedback.description}</CardDescription>
            </CardHeader>
            <CardContent className="flex flex-col items-center gap-4">
                <div className="relative flex items-center justify-center w-32 h-32 md:w-40 md:h-40">
                    <svg className="w-full h-full transform -rotate-90">
                        <circle className="text-secondary" strokeWidth="10" stroke="currentColor" fill="transparent" r="58" cx="64" cy="64" />
                        <circle
                          className="text-primary"
                          strokeWidth="10"
                          strokeDasharray={2 * Math.PI * 58}
                          strokeDashoffset={(2 * Math.PI * 58) * (1 - percentage / 100)}
                          strokeLinecap="round"
                          stroke="currentColor"
                          fill="transparent"
                          r="58"
                          cx="64"
                          cy="64"
                          style={{ transition: 'stroke-dashoffset 1s ease-out' }}
                        />
                    </svg>
                    <span className="absolute text-3xl md:text-4xl font-bold">{score}/{quizData!.questions.length}</span>
                </div>
                <p className="text-base md:text-lg">You scored {percentage}% on the "{topic}" quiz.</p>
            </CardContent>
            <CardFooter className="flex flex-col sm:flex-row gap-2">
                <Button variant="outline" className="w-full" onClick={() => restartQuiz(false)}>
                    <Repeat className="mr-2 h-4 w-4" />
                    Retry Quiz
                </Button>
                <Button className="w-full" onClick={() => restartQuiz(true)}>
                    <Home className="mr-2 h-4 w-4" />
                    New Topic
                </Button>
            </CardFooter>
        </Card>
    );
  };


  return (
    <div className="w-full p-2 md:p-0">
      {appState === 'topic' && renderTopicSelector()}
      {appState === 'loading' && renderLoading()}
      {appState === 'quiz' && renderQuiz()}
      {appState === 'results' && renderResults()}
    </div>
  );
}
